"""Embed JSON data into index.html for local browser testing (no HTTP server needed)."""
import json, re, os

os.chdir(os.path.dirname(os.path.abspath(__file__)))

with open("data/dealer_outstanding.json", encoding="utf-8") as f:
    dealer = json.load(f)
with open("data/daily_collection.json", encoding="utf-8") as f:
    daily = json.load(f)
with open("data/cohort.json", encoding="utf-8") as f:
    cohort = json.load(f)

with open("index.html", encoding="utf-8") as f:
    html = f.read()

# Replace the three jf() fetch calls + boot with inline data
inject = f"""
<script>
// Embedded data (generated by build_local.py)
const _DATA = {{
  dealer_outstanding: {json.dumps(dealer)},
  daily_collection: {json.dumps(daily)},
  cohort: {json.dumps(cohort)}
}};
async function jf(p) {{
  const k = p.replace('data/','').replace('.json','');
  return _DATA[k] || null;
}}
</script>
"""

# Insert before first <script>
html = html.replace("<script>\n// ── utils", inject + "<script>\n// ── utils", 1)

with open("local.html", "w", encoding="utf-8") as f:
    f.write(html)

print(f"local.html written ({os.path.getsize('local.html')//1024} KB)")
print(f"  dealer_outstanding: {len(dealer)} rows")
print(f"  daily_collection:   {len(daily)} rows")
print(f"  cohort:             {len(cohort)} rows")
